"""add_sector_to_stocks_and_fund_compositions

Revision ID: 43783ea4d696
Revises: 31c584b79624
Create Date: 2026-06-14 01:11:22.810230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '43783ea4d696'
down_revision: Union[str, None] = '31c584b79624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('xirr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_holdings_asset_class', 'holdings', ['asset_class'], unique=False)
    op.create_index('idx_holdings_instrument_type', 'holdings', ['instrument_type'], unique=False)
    op.create_index('idx_holdings_user_active', 'holdings', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_holdings_user_id', 'holdings', ['user_id'], unique=False)
    op.add_column('fund_compositions', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('stocks', sa.Column('sector', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'sector')
    op.drop_column('fund_compositions', 'sector')
    op.drop_index('idx_holdings_user_id', table_name='holdings')
    op.drop_index('idx_holdings_user_active', table_name='holdings')
    op.drop_index('idx_holdings_instrument_type', table_name='holdings')
    op.drop_index('idx_holdings_asset_class', table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
