"""add news highlights table

Revision ID: f2bfaa555daa
Revises: 43783ea4d696
Create Date: 2026-09-27 11:39:28.906808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2bfaa555daa'
down_revision: Union[str, None] = '43783ea4d696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_highlights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('holding_name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_highlights_user_id', 'news_highlights', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_highlights_user_id', table_name='news_highlights')
    op.drop_table('news_highlights')
    # ### end Alembic commands ###
